<?php
//2013-08-08 20:23:48 Created
$__XWB_SET=array (
  'wb_addr_display' => 1,
  'is_wbx_display' => 0,
  'wbx_width' => 180,
  'wbx_height' => 75,
  'wbx_style' => 1,
  'wbx_line' => 1,
  'wbx_is_title' => 0,
  'wbx_is_blog' => 0,
  'wbx_is_fans' => 0,
  'wbx_url' => 'http://service.t.sina.com.cn/widget/WeiboShow.php?uname=xweibo%E6%B5%8B%E8%AF%95%E5%B8%90%E5%8F%B7&width=180&height=500&skin=4&isTitle=1&isWeibo=1&isFans=1&fansRow=2&__noCache=1293085731965',
  'is_account_binding' => 1,
  'is_synctopic_toweibo' => 1,
  'is_syncreply_toweibo' => 1,
  'is_syncdoing_toweibo' => 1,
  'is_syncblog_toweibo' => 1,
  'is_syncshare_toweibo' => 1,
  'is_syncarticle_toweibo' => 1,
  'is_rebutton_display' => 1,
  'is_rebutton_relateUid_assoc' => 1,
  'is_tips_display' => 1,
  'is_signature_display' => 1,
  'is_sync_face' => 1,
  'is_upload_image' => 1,
  'wbx_medal_update_time' => 1800,
  'wbx_share_time' => 5,
  'is_display_login_button' => 1,
  'is_display_login_button_in_fastpost_box' => 1,
  'display_login_button_hookname' => 'global_login_extra',
  'link_visit_promotion' => 0,
  'wbx_huwb_update_time' => 3,
  'is_pushback_open' => 0,
  'pushback_authkey' => '',
  'pushback_to_thread' => 0,
  'pushback_to_blog' => 0,
  'pushback_to_doing' => 0,
  'pushback_to_article' => 0,
  'pushback_to_share' => 0,
  'pushback_fromid' => 0,
  'bind_btn_usernav' => 1,
  'pushback_username' => '',
  'pushback_uid' => 0,
  'switch_to_xweibo' => 0,
  'url_to_xweibo' => '',
  'encrypt_key' => '719ad247ae8229b530b6b473a0d25596',
  'baseurl_to_xweibo' => '',
  'space_card_weiboinfo' => 1,
  'display_ow_in_forum_index' => 0,
  'is_tgc_display' => 0,
);